Org change to indix-eng
indix/indix.github.io pull request #4
Opened 2016-09-26 15:39 UTC by bigomega

Also adding two factor authentication

2016-09-26 15:42 UTC, ashwanthkumar commented on helpers/github_helpers.rb
> +      c.connection_options = {headers: {"X-GitHub-OTP" => config[:github_tfa]}}
@bigomega This works even when the value is false?

2016-09-26 15:43 UTC, ashwanthkumar commented on helpers/github_helpers.rb
> +    config[:github_tfa] == false
Don't we need `and` or `&&` like that here ?

2016-09-26 15:45 UTC, ashwanthkumar commented on helpers/github_helpers.rb
> +    print(", " + repo)
Do we need this print statement here?

2016-09-26 15:47 UTC, ashwanthkumar commented on deploy.sh
>    git clone -b master git@github.com:ind9/ind9.github.io $DEPLOY_FOLDER
@bigomega I know github does re-directs but it's good to change this too no?

2016-09-26 15:49 UTC, ashwanthkumar requested changes
Also SnapCI has detected the rename of the repo, it would be great if we can change the build badge on README as well. I wasn't able to comment that line in the changes page.

2016-09-26 15:58 UTC, bigomega commented on deploy.sh
>    git clone -b master git@github.com:ind9/ind9.github.io $DEPLOY_FOLDER
My bad, sorry. Good catch.

2016-09-26 16:35 UTC, bigomega commented on helpers/github_helpers.rb
> +      c.connection_options = {headers: {"X-GitHub-OTP" => config[:github_tfa]}}
Done

2016-09-26 16:35 UTC, bigomega commented on helpers/github_helpers.rb
> +    config[:github_tfa] == false
Done

2016-09-26 16:36 UTC, bigomega commented on helpers/github_helpers.rb
> +    print(", " + repo)
Yes, it gives a decent idea of progress for few seconds when you're waiting for the page to load.

2016-09-26 16:37 UTC, bigomega commented
@ashwanthkumar can you make the snap-ci changes? I am not sure about it

2016-09-26 16:46 UTC, ashwanthkumar commented on helpers/github_helpers.rb
> +    print(", " + repo)
But this runs while deploying only no? I could well be wrong.

2016-09-26 16:48 UTC, ashwanthkumar commented on helpers/github_helpers.rb
> +      c.connection_options = {headers: {"X-GitHub-OTP" => config[:github_tfa]}}
I think I asked this earlier - does this work if TFA is set to false ?

2016-09-26 16:48 UTC, manojlds commented
Taking over this change. Will do the snap-ci and other changes. @bigomega @ashwanthkumar

2016-09-26 17:17 UTC, manojlds commented on helpers/github_helpers.rb
> +    throw "Authentication missing" if config[:github_auth].empty? or config[:github_tfa].empty?
Why this? It was supposed to be that the AUTH is optional.

2016-09-26 17:17 UTC, manojlds commented on helpers/github_helpers.rb
> +    throw "Authentication missing" if config[:github_auth].empty? or config[:github_tfa].empty?
Also there is a runtime issue with error `undefined method `empty?' for false:FalseClass`

2016-09-26 17:49 UTC, manojlds commented
Verified that 2fa is not needed if we use personal auth token (which is what we have been using.) Just need to set `GITHUB_AUTH` as `<user>:<token>`. Removing those changes

2016-09-26 17:59 UTC, merged

2016-09-27 04:48 UTC, bigomega commented on helpers/github_helpers.rb
> +    print(", " + repo)
No, it ran every time I refreshed page while middleman was serving.

2016-09-27 05:02 UTC, bigomega commented
With or without any authentication, I get the authentication error.
```bash
$ bundle exec middleman serve
# ---- OR ----
$ GITHUB_API=bharathraja@live.com:3029b5***** bundle exec middleman serve
```
**Github::Error::Unauthorized: GET https://api.github.com/repos/indix-eng/gocd-s3-artifacts/contributors: 401 - Must specify two-factor authentication OTP code.
See: https://developer.github.com/v3/auth#working-with-two-factor-authentication**

@manojlds This is why I had to add TFA. If it's working for you, it's likely some info is missing in the readme.

2016-09-27 05:05 UTC, manojlds commented on helpers/github_helpers.rb
> +    print(", " + repo)
Yeah. auth is meant for deploy time, and client side rendering for dev time. If you set auth in dev, it will fetch info server side for every reload.

2016-09-27 06:07 UTC, bigomega commented on helpers/github_helpers.rb
> +    print(", " + repo)
The contributors are fetched by the server. If I don't have auth in dev time, I don't see the contributors list.